substitutions:
  device_name: helo

external_components:
  - source: esphome/components

esphome:
  name: ${device_name}
  comment: ${device_name} sauna controller
  area: Sauna

esp32:
  #change right board for your device
  board: m5stack-atom
  framework:
    type: esp-idf

# Enable logging
logger:
  level: DEBUG
  # disable putting logging on the HW uart
  baud_rate: 0

# Enable Home Assistant API
api:

# Enable OTA updates and read logs with wifi
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  #recommended to manually configure ip address
  manual_ip:
    # Set this to the IP of the ESPhome device
    static_ip: 192.168.1.174
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

uart:
  # change right pins for your ESPhome device
  tx_pin: GPIO26
  rx_pin: GPIO32
  baud_rate: 19200
  data_bits: 8
  parity: EVEN
  stop_bits: 1

sauna360:

sensor:
- platform: wifi_signal
  name: "${device_name} WiFi Signal"
  update_interval: 60s
- platform: sauna360
  current_temperature:
    name: "Current Temperature"

button:
- platform: sauna360
  heater_on:
    name: "Heater On"
- platform: sauna360
  heater_off:
    name: "Heater Off"